dist: bionic
language: php

env:
  global:
    - setup=stable
    - xdebug=true

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.1
      env: setup=lowest
    - php: 7.2
    - php: 7.2
      env: setup=lowest
    - php: 7.3
      env: xdebug=false
    - php: 7.3
      env:
        - xdebug=false
        - setup=lowest
    - php: 7.4
      env: xdebug=false
    - php: 7.4
      env:
        - xdebug=false
        - setup=lowest

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - if [[ $xdebug = 'true' ]]; then phpenv config-rm xdebug.ini; fi

install:
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest --prefer-lowest; fi

script:
  - composer phpunit
